
export const AUTH = {
    SIGN_UP_LOADING: 'SIGN_UP_LOADING',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    SIGN_UP_LOGOUT: 'SIGN_UP_LOGOUT',

    SIGN_IN_API_LOADING: 'SIGN_IN_API_LOADING',
    SIGN_IN_FB_LOADING: 'SIGN_IN_FB_LOADING',
    SIGN_IN_API_SUCCESS: 'SIGN_IN_API_SUCCESS',
    SIGN_IN_API_ERROR: 'SIGN_IN_API_ERROR',
    SIGN_IN_API_LOGOUT: 'SIGN_IN_API_LOGOUT',

    CHANGE_USER_MAIN_LOADING: 'CHANGE_USER_MAIN_LOADING'
};

export const HOME = {
    CATEGORIES_LOADING: 'CATEGORIES_LOADING',
    CATEGORIES_SUCCESS: 'CATEGORIES_SUCCESS',
    CATEGORIES_ERROR: 'CATEGORIES_ERROR',

    CATEGORIES_BY_BRAND_LOADING: 'CATEGORIES_BY_BRAND_LOADING',
    CATEGORIES_BY_BRAND_SUCCESS: 'CATEGORIES_BY_BRAND_SUCCESS',
    CATEGORIES_BY_BRAND_ERROR: 'CATEGORIES_BY_BRAND_ERROR',
    CLEAR_CATEGORIES_BY_BRAND: 'CLEAR_CATEGORIES_BY_BRAND',

    CHANGE_CATEGORY: 'CHANGE_CATEGORY',
    CHANGE_SUBCATEGORY: 'CHANGE_SUBCATEGORY',

    SUBCATEGORIES_LOADING: 'SUBCATEGORIES_LOADING',
    SUBCATEGORIES_SUCCESS: 'SUBCATEGORIES_SUCCESS',
    SUBCATEGORIES_ERROR: 'SUBCATEGORIES_ERROR',

    BRANDS_LOADING: 'BRANDS_LOADING',
    BRANDS_SUCCESS: 'BRANDS_SUCCESS',
    BRANDS_ERROR: 'BRANDS_ERROR',

    PRODUCTS_LOADING: 'PRODUCTS_LOADING',
    PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
    PRODUCTS_ERROR: 'PRODUCTS_ERROR',

    CATEGORY_PRODUCTS_LOADING: 'CATEGORY_PRODUCTS_LOADING',
    CATEGORY_PRODUCTS_SUCCESS: 'CATEGORY_PRODUCTS_SUCCESS',
    CATEGORY_PRODUCTS_ERROR: 'CATEGORY_PRODUCTS_ERROR',
    CATEGORY_PRODUCTS_CLEAR: 'CATEGORY_PRODUCTS_CLEAR',

    CHANGE_PRODUCT: 'CHANGE_PRODUCT',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
    PRODUCT_ERROR: 'PRODUCT_ERROR',

    CHANGE_KEY: 'CHANGE_KEY',

    SET_FILTERS: 'SET_FILTERS',
    CLEAR_FILTERS: 'CLEAR_FILTERS',

    CHANGE_DEGREES: 'CHANGE_DEGREES',
    ADD_BRAND: 'ADD_BRAND',

    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
    CLEAR_SEARCH_VALUE: 'CLEAR_SEARCH_VALUE'
};

export const CHAT = {
    LOAD_MESSAGES: 'LOAD_MESSAGES',
    SET_MESSAGES_SUCCESS: 'SET_MESSAGES_SUCCESS',
    SET_MESSAGES_ERROR: 'SET_MESSAGES_ERROR'
};

export const SELL = {
    PRODUCT_LOADING: 'PRODUCT_LOADING',

    EDIT_LISTING: 'EDIT_LISTING',
    CLEAR_LISTING: 'CLEAR_LISTING'
};

export const DEGREE = {
    CHANGE_VALUE: 'CHANGE_VALUE'
};

export const CART = {
    CONSUMER_CART_LOADING: 'CONSUMER_CART_LOADING',

    CONSUMER_CART_INFO_LOADING: 'CONSUMER_CART_INFO_LOADING',
    CONSUMER_CART_INFO_SUCCESS: 'CONSUMER_CART_INFO_SUCCESS',
    CONSUMER_CART_INFO_ERROR: 'CONSUMER_CART_INFO_ERROR',

    ADD_TO_CART_LOADING: 'ADD_TO_CART_LOADING',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_ERROR: 'ADD_TO_CART_ERROR',

    PROMO_CODE_LOADING: 'PROMO_CODE_LOADING',

    DELETE_FROM_CART: 'DELETE_FROM_CART',

    ADD_CART_ADDRESS: 'ADD_CART_ADDRESS',

    CUSTOMER_TO_CART_LOADING: 'CUSTOMER_TO_CART_LOADING'
};

export const PAYMENT = {
    PAY_LIST_LOADING: 'PAY_LIST_LOADING',
    PAY_LIST_SUCCESS: 'PAY_LIST_SUCCESS',
    PAY_LIST_ERROR: 'PAY_LIST_ERROR',

    ADD_PAY_METHOD_LOADING: 'ADD_PAY_METHOD_LOADING'
};

export const CHECK = {
    VISIBLE_BILLING_ADDRESS: 'VISIBLE_BILLING_ADDRESS'
};

export const SELLER = {
    SHOP_INFO_LOADING: 'SHOP_INFO_LOADING',
    SHOP_INFO_SUCCESS: 'SHOP_INFO_SUCCESS',
    SHOP_INFO_ERROR: 'SHOP_INFO_ERROR',

    SHOP_EDIT_INFO_LOADING: 'SHOP_EDIT_INFO_LOADING'
};

export const WATCH = {
    WATCH_LIST_INFO_LOADING: 'WATCH_LIST_INFO_LOADING',
    WATCH_LIST_INFO_SUCCESS: 'WATCH_LIST_INFO_SUCCESS',
    WATCH_LIST_INFO_ERROR: 'WATCH_LIST_INFO_ERROR',

    ADD_TO_WATCH_LIST: 'ADD_TO_WATCH_LIST',
    DELETE_FROM_WATCH_LIST: 'DELETE_FROM_WATCH_LIST'
};

export const CUSTOMER = {
    MY_INFO_LOADING: 'MY_INFO_LOADING',
    MY_INFO_SUCCESS: 'MY_INFO_SUCCESS',
    MY_INFO_ERROR: 'MY_INFO_ERROR',

    CHANGE_USER_ADDRESS: 'CHANGE_USER_ADDRESS',
    DELETE_USER_ADDRESS: 'DELETE_USER_ADDRESS'
};